ethereum-optimism/asterisc

- .github/workflows/ci.yaml
- rvgo/fast/memory_test.go
Adds a CI workflow with go build caching for the `rvgo` tests. Also templates out a `golangci-lint` job, which is currently throwing up a ton of errors. Will follow up with another PR to fix those and enable that job.
Also fixes the "fuller tree" test in `TestMemoryMerkleProof`, where the test assertion assumed that the `0x2A` byte would be right-aligned in the 32-bit slice of the proof. `SetUnaligned` always writes the bytes passed verbatim starting at the given memory address, so the 4 byte proof element should be `0x2a000000` rather than `0x0000002a`.
> feat: Add CI + fix test

- .github/workflows/ci.yaml
- .gitmodules
- rvgo/fast/evm.go
- rvgo/fast/witness.go
- rvsol/src/PreimageKeyLib.sol
- rvsol/src/PreimageOracle.sol
- rvsol/src/interfaces/IPreimageOracle.sol
- rvsol/test/PreimageOracle.t.sol
Adds local preimage support. Referenced from https://github.com/ethereum-optimism/optimism/pull/6373. 
This PR
1. Refactors contract implementation by using `PreimageKeyLib.sol`.
2. `PreimageOracle.sol` now satisfies `IPreimageOracle.sol`, which is crucial to integrate asterisc with upstream contracts(such as dispute game)
3. Implements `LoadLocalData` method to properly provide localdata.
4. Removes cheater methods because `LoadLocalData` method is implemented.
5. Enables CI to run foundry tests.
There are some duplications: Most of `PreimageKeyLib.sol` and entire `IPreimageOracle.sol` compared to upstream cannon. This diff may be removed in the following PRs(not yet opened).
**Tests**
Cherry-picked tests from https://github.com/ethereum-optimism/optimism/pull/6373. Use …
> feat: Local Preimage Support

- rvsol/src/PreimageOracle.sol
- rvsol/test/PreimageOracle.t.sol
Mirrors https://github.com/ethereum-optimism/optimism/pull/9035 which corrects off by one error in preimage oracle contract.
**Tests**
Adds single test which is also mirrored.
**Additional context**
Current dependencies on/for this PR:
- master
- **PR** https://github.com/ethereum-optimism/asterisc/pull/9 
-  **PR** https://github.com/ethereum-optimism/asterisc/pull/10
- **PR** https://github.com/ethereum-optimism/asterisc/pull/11 (this PR)
- **PR** https://github.com/ethereum-optimism/asterisc/pull/12
> fix: PreimageOracle off-by-one

- rvgo/test/evm_test.go
- rvsol/src/RISCV.sol
- rvsol/test/RISCV.t.sol
Upstream cannon uses step contract name following its architecture: `MIPS.sol`. Currently asterisc uses step contract name as `Step.sol`. Rename `Step.sol` to `RISCV.sol` for consistency.
**Tests**
None
**Additional context**
Current dependencies on/for this PR:
- master
- **PR** https://github.com/ethereum-optimism/asterisc/pull/13 
- **PR** https://github.com/ethereum-optimism/asterisc/pull/14 (this PR)
> feat: Rename `Step.sol` to `RISCV.sol`

- rvgo/cmd/load_elf.go
- rvgo/cmd/metadata.go
- rvgo/cmd/process_preimage_oracle.go
- rvgo/cmd/run.go
- Bring the missing utility feature [`Metadata`](https://github.com/ethereum-optimism/optimism/blob/develop/cannon/mipsevm/metadata.go) from Cannon.
- Small fix for `ProcessPreimageOracle`: Remove an unnecessary method.
> feat: Support metadata for symbol lookup

- docs/golang.md
- rvgo/fast/elf.go
- rvgo/fast/vm.go
- rvgo/slow/vm.go
- rvsol/src/RISCV.sol
- tests/go-tests/Makefile
- Patch more symbols (referenced from Cannon)
- Ignore unnecessary system calls
- `epoll_create1`
- `epoll_ctl`
- `pipe2`
- `readlinkat`
- `newfstatat`
- `newuname`
- `munmap`
- `getrandom`
- TODO: is it ok?
- Add softfloat gcflag
**Test**
Manually run op-program(v.1.5.1) by `run` command on the local devnet and op-sepolia, and it works :)
> Fix for running op-program

- .github/workflows/ci.yaml
- rvgo/scripts/go-ffi/bin.go
- rvgo/scripts/go-ffi/differential-testing.go
- rvgo/scripts/go-ffi/utils.go
- rvsol/test/CommonTest.sol
- rvsol/test/RISCV.t.sol
Implements FFI interface for fetching snapshot data on foundry testing. Subset of https://github.com/ethereum-optimism/optimism/pull/6638. 
For unknown reason, importing `@optimism/src/libraries/DisputeTypes.sol` causes below build error.
```
Error: 
Compiler run failed:
Error (2333): Identifier already declared.
--> lib/optimism/packages/contracts-bedrock/src/dispute/lib/LibGameId.sol:9:1:
|
9 | library LibGameId {
| ^ (Relevant source part starts here and spans across multiple lines).
Note: The previous declaration is here:
--> lib/optimism/packages/contracts-bedrock/src/dispute/lib/LibGameId.sol:4:1:
|
4 | import "src/libraries/DisputeTypes.sol";
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I could not resolve this, so first hardcoded the `VMStatuses` for temporary …
> feat: Asterisc contracts VM tests - FFI

- .gitignore
- Makefile
- rvgo/Makefile
- rvsol/Makefile
Implement basic make commands
- `build`: build each components
- `clean`: remove build artifacts
- `test`: run tests
> Implement basic make command for build and test

- Makefile
- rvgo/fast/vm.go
- rvgo/slow/vm.go
- rvgo/test/syscall_test.go
- rvsol/src/RISCV.sol
Following up on the previous PR(https://github.com/ethereum-optimism/asterisc/pull/21), added fuzz tests for rest of syscalls.
- FuzzStateSyscallBrk
- FuzzStateSyscallMmap
- FuzzStateSyscallFcntl
- FuzzStateSyscallOpenat
- FuzzStateSyscallClockGettime
- FuzzStateSyscallClone
- FuzzStateSyscallGetrlimit
- FuzzStateRead
- stdin, errors
- FuzzStateWrite
- stdout, stderr, errors
And fixed getrlimit syscall implementation to return 0 ([ref](https://man7.org/linux/man-pages/man2/getrlimit.2.html#RETURN_VALUE))
> More syscall fuzz test

- .github/workflows/ci.yaml
- rvsol/Makefile
- rvsol/foundry.toml
- rvsol/src/RISCV.sol
- rvsol/test/CommonTest.sol
- rvsol/test/RISCV.t.sol
- Add config for forge fmt. referred to optimism contracts-bedrock package
- Add make command for rvsol lint
- Add CI job for rvsol lint
- Fix lint errors
- Add license identifier
> rvsol: Lint CI job

- .github/workflows/ci.yaml
- .golangci.yml
- rvgo/Makefile
- rvgo/cmd/load_elf.go
- rvgo/cmd/process_preimage_oracle.go
- rvgo/fast/memory.go
- rvgo/fast/state.go
- rvgo/fast/vm.go
- rvgo/fast/witness.go
- rvgo/fast/yul256.go
- rvgo/fast/yul64.go
- rvgo/slow/yul64.go
- rvgo/test/evm_test.go
- Add config for golangci-lint, referred to optimism contracts-bedrock package
- Add make command for rvgo lint
- Add CI job for rvgo lint
- Fix lint errors
- Ignored unused errors for utils for now
- Additionally, update deprecated github action version
> rvgo: Lint CI job

- rvsol/test/RISCV.t.sol
DisputeTypes.sol dependency issue has been resolved in the previous [PR](https://github.com/ethereum-optimism/asterisc/pull/26). So we can now import VMStatus.
> rvsol: Import VMStatus from DisputeTypes.sol

- rvgo/fast/vm.go
- rvgo/test/syscall_test.go
Fast VM's storeMemUnaligned() does not set the right part of the unaligned data. However, the bug is not tested via fuzz test case because it uses only aligned addresses.
I fixed the bug to make it behave the same way with [slow VM](https://github.com/ethereum-optimism/asterisc/blob/master/rvgo/slow/vm.go#L430) and [rvsol](https://github.com/ethereum-optimism/asterisc/blob/master/rvsol/src/RISCV.sol#L730).
> Fix fast VM storeMemUnaligned()

- rvgo/fast/vm.go
- rvgo/slow/vm.go
- rvgo/test/syscall_test.go
- rvsol/src/RISCV.sol
The original implementation of the `clock_gettime` syscall does not allow a misaligned address for the destination. However, at the same time, it calls `storeMemUnaligned()` twice, which makes the proof size longer. 
I tried to find the spec of Linux syscall to know if `clock_gettime` should allow a misaligned destination, but it seems there's no spec about that, and it depends on the kernel implementation.
I read some Linux kernel source code, and it seems RISC-V allows a misaligned destination. (see following files: [`kernel/time/posix-timers.c`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/kernel/time/posix-timers.c?h=v6.8.2#n1132), [`kernel/time/time.c`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/kernel/time/time.c?h=v …
> Allow misaligned clock_gettime syscall

- rvsol/scripts/Deploy.s.sol
Adding diff from https://github.com/ethereum-optimism/optimism/pull/9823. Required for adding asterisc game type and asterisc deployment for devnet and CI.
> Update optimism monorepo which supports asterisc game type and deployments

- rvgo/slow/vm.go
- rvgo/test/syscall_test.go
https://github.com/ethereum-optimism/asterisc/pull/31 did not have linter enabled.
> rvgo: Fix lint

- rvgo/cmd/witness.go
Make `witness` command save witness and statehash to json.
```
type WitnessOutput struct {
Witness   []byte   `json:"witness"`
StateHash [32]byte `json:"stateHash"`
}
```
**Tests**
Manually tested using the absolute prestate of op-program on riscv.
Command: `./asterisc witness --input prestate.json --output -`
Output:
```
{
"witness": "wOSi8Cm62dDmKt1OGwxlLrSznk6zE4ghp7evP1rfrXYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIGCAAAAAAAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
```
> rvgo: Witness cmd saves witness & stateHash to json

- rvgo/cmd/load_elf.go
- rvgo/cmd/run.go
- rvgo/fast/state.go
op-challenger must import FPVM codes to calculate witness and statehash itself. By saving witness and statehash to the state struct, we remove this burden.
golint ci fails. Fixed at https://github.com/ethereum-optimism/asterisc/pull/38 and will rebase.
> rvgo: Embed witness and stateHash to state

- rvsol/scripts/Artifacts.s.sol
- rvsol/scripts/Config.sol
- rvsol/scripts/Deploy.s.sol
- rvsol/scripts/create_poststate_after_deployment.sh
To run op-e2e, we need artifacts present at the test root. This patch creates L1 alloc which includes asterisc included, and asterisc contract's address.
To elaborate, we need these files from [here](https://github.com/ethereum-optimism/optimism/blob/069f9c22775805c851919a594de817c8843182b6/op-e2e/config/init.go#L49-L51):
```go
defaultL1AllocsPath := filepath.Join(root, ".devnet", "allocs-l1.json")
defaultL1DeploymentsPath := filepath.Join(root, ".devnet", "addresses.json")
defaultDeployConfigPath := filepath.Join(root, "packages", "contracts-bedrock", "deploy-config", "devnetL1.json")
```
The newly added deployment scripts `create_poststate_after_deployment.sh` loads L1 alloc which did not had asterisc deployed, then deploy asterisc, and dump L1 alloc to json state.
> rvsol: Dump post state after asterisc deployment on devnet

- rvsol/foundry.toml
Update optimism submodule version to the current develop branch(https://github.com/ethereum-optimism/optimism/commit/3d27411a05472bc8eba15d93cfc4ba092d586bd6)
> Update optimism submodule version to 3d27411

- .circleci/config.yml
Adds CI to calculate asterisc's absolute prestate, to prepare op-e2e tests for asterisc. To do this, 
1. Build op-program and compile op-program to riscv
2. Ask asterisc binary to create absolute prestate from op-program binary.
Example pipeline at [here](https://app.circleci.com/pipelines/github/ethereum-optimism/asterisc/56/workflows/103dea74-37ca-4f84-b6e8-c4c29b5ba953?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary):
> ci: make absolute prestate for asterisc

- .circleci/config.yml
Adds CI step for generating devnet alloc where asterisc is deployed. Patch `address.json`, `allocs-l1.json`, and `.deploy` for preparing op-e2e.
> ci: Devnet alloc after asterisc deployment

- rvgo/cmd/run.go
- rvgo/fast/instrumented.go
Add stopAtPreimage flag to `run` command. This implementation mirrors https://github.com/ethereum-optimism/optimism/pull/9687.
This will be tested by e2e tests.
> rvgo:Add stopAtPreimage flag

- .gitignore
- Makefile
- rvsol/scripts/devnet_allocs.sh
Adds `make devnet-allocs` and other aux command to run op-e2e locally. Similar to `make devnet-allocs` at monorepo.
To cleanly build, run `make devnet-clean` then run `make devnet-allocs`.
> test: Devnet Alloc for local testing

- rvgo/fast/state.go
- rvgo/fast/vm.go
- rvgo/test/syscall_test.go
Fix hint writing logic at `vm.go`. Equal bug compared with https://github.com/ethereum-optimism/optimism/pull/10514.
**Tests**
Mirrored unit test and fuzz test.
Ensured syscall instruction is 4 bytes written, for avoiding fuzz test failure.
> rvgo: Fix inverted hint writing conditional check

- rvsol/foundry.toml
- rvsol/scripts/Deploy_Stage_1_4.sol
- rvsol/scripts/deploy_stage_1_4.sh
Added deployment script to deploy necessary contracts for stage 1.4, referring to `FPACOPS.sol` and `Deploy.s.sol` from the monorepo. I chose not to use safe contracts to make the implementation more simple. All the new contract's ownership will be set to deployer, not the safe contract.
Deploying below contract is necessary:
- Proxies: `ProxyAdmin`, `DisputeGameFactoryProxy`, `AnchorStateRegistryProxy`
- Implementations: `DisputeGameFactory`, `AnchorStateRegistry`, `RISCV`
We reuse existing contracts. They are already deployed:
- `PreimageOracle` for deploying `RISCV`
- `DelayedWETH` for creating initial Fault Dispute Game.
After deployment, we `setImplementation` and `setInitBond` for asterisc by interacting with DGF.
```solidity
DisputeGameFactory factory = …
```
> scripts: Stage 1.4 deployment

- rvgo/fast/memory.go
If `l > PageKeySize+1` is true, it will already run into the `l > PageKeySize` branch above and return.
> remove an impossible branch

- funding.json
Add: funding.json for Retro Funding Round 5
Sunnyside Labs is applying to Retro Funding 5. From Retro Funding Round 5, the application is required to add the JSON file to prove that the applicant is a contributor to the repository. 
**Tests**
N/A
**Additional context**
N/A
**Metadata**
N/A
> Create: funding.json for Retro Funding Round 5

- Dockerfile.release
Moves the executable from `/asterisc-bin` to `/usr/local/bin/asterisc` so it is on the default path. Also enables caching of go build artefacts to speed up rebuilding and sets entry point to `asterisc` so its easy to actually execute the docker image.
> Put asterisc executable on the default PATH in docker image.

- rvgo/fast/vm.go
- rvgo/slow/vm.go
- rvgo/test/syscall_test.go
- rvsol/src/RISCV.sol
Optimism has recently updated its go version to go1.22. 
However, updating to go1.22 introduces an error in the vm: `cannot open standard fds`. This is because go added checks for standard file descriptors: https://github.com/golang/go/commit/d4dd1de19fcef835fca14ad8cb590dbfcf8e9859.
This can be fixed by adding support for handling F_GETFD in the vm. 
A corresponding PR for cannon is in https://github.com/ethereum-optimism/optimism/pull/12050
**Tests**
- All existing test suites passes
- New fuzz tests for testing the correct behavior of F_GETFD
> Add support for F_GETFD in order to support go1.22+

- docs/radix-memory.md
- rvgo/fast/memory.go
- rvgo/fast/memory_benchmark_test.go
- rvgo/fast/memory_test.go
- rvgo/fast/page.go
- rvgo/fast/radix.go
Currently, Asterisc's memory layout is constructed using merkle tree represented as hashmaps where keys are a generalized index and values are the merkle root of the sub-tree or the node.
This design is identical to Cannon, and has some room for improvements. Therefore, in order to make Asterisc more memory efficient, we propose modifying the memory layout as follows.
1. Modify Asterisc to use radix trie instead of hashmap.
Currently, the memory of asterisc is laid out as follows. 
```go
nodes map[uint64]*[32]byte
```
We can modify it to something like:
```go
type RadixNode struct {
Children [1  << 12]*RadixNode
Hash [1 << 12][32]byte		
HashExists [(1 << 12) / 64]uint64
HashValid  [(1 << 12) / 64]uint64
}
```
1. Tune the radix trie's branching factor.
In order to better accommodate the …
> Convert rvgo's memory implementation to radix trie

- rvsol/src/RISCV.sol
This PR fixes stack too deep error when compiling with the optimizer off. This is important to be able to run forge coverage and generate test coverage reports.
> fixes stack too deep error when compiling with the optimizer off

- docs/riscv.md
Hi!
Updated the broken link for the RV32 reference card to the correct release URL:
https://github.com/jameslzhu/riscv-card/releases/download/latest/riscv-card.pdf
This change aligns with the update made in [commit 6628be3](https://github.com/jameslzhu/riscv-card/commit/6628be3cca53b590896ae7a72a9d9446eee7bfd1).
> fix: broken link riscv.md

- rvgo/fast/vm.go
- rvgo/slow/vm.go
- rvsol/src/RISCV.sol
- rvsol/test/RISCV.t.sol
The [RISC-V specifications](https://riscv.org/specifications/ratified/) indicate the following in section "2.5.1. Unconditional Jumps".
> The JAL and JALR instructions **will generate an instruction-address-misaligned exception if the target
address is not aligned to a four-byte boundary**.
However, the three implementations (fast, slow, solidity) succeed when a unconditional jump instruction (JAL or JALR) sets a program counter `pc` not aligned on 4 bytes.
The jump opcodes (`0x67` and `0x6F`) implementation should raise an exception when the new program counter `pc` is not aligned on 4 bytes.
> Add 4-byte alignment check on pc in JAL/JALR instructions

- rvgo/slow/vm.go
The Go slow implementation is intended to mirror the Solidity implementation. For this, it takes the calldata as input.
However, the slow implementation lacks a check that is abstracted in the Solidity implementation: the function selector.
As the function selector is not checked, calldata with incorrect selector will be executable on the slow implementation but will revert on the Solidity smart contract.
Ensure on the slow implementation that the first 4 bytes of calldata correspond to the correct function selector.
> Add function selector check for slow vm

- docs/radix-memory.md
This pull request addresses typos in the `radix-memory.md` file:
- Corrected "addresse" to "addresses" for grammatical accuracy.
- Improved phrasing for consistency and professionalism.
1. Updated "addresse" to "addresses" in the context of memory operations.
2. Ensured proper grammar in the documentation without altering its technical content.
These corrections enhance the documentation's readability and maintain its technical accuracy.
This is a minor documentation fix and does not affect the codebase's functionality.
> fix typo Update radix-memory.md

- rvsol/src/RISCV.sol
Using bitwise not on a 0 padded uint256 value results in the value being uint256.max when it should be 1. 
Use eq(x,0) to check for not instead.
> Fix != 0 check in rvsol

- rvsol/src/RISCV.sol
Multiple functions are implemented to calculate the state offset of a given field. However, the offset of a field depends on the offset of the previous field until reaching the first offset. As a given offset depends on the previous offset, the code consumes a lot of gas for values that will never change.
For example, calling `stateOffsetPreimageKey` would consume approximately 444 gas while `stateSize` consume 1096 gas. Both will always return the same value.
Note that Go slow and fast implementations do not need this type of optimization as computations are cheaper.
> Hardcord state offset values to save gas and execution time

- rvgo/fast/vm.go
- rvgo/slow/vm.go
- rvsol/src/RISCV.sol
- rvsol/test/RISCV.t.sol
The RISCV implementations (sol/fast/slow) return incorrect results, in conflict with the RISCV specification, for all 32-bit division operations (DIVW, DIVUW, REMW, REMUW) when the divisor is zero.
All word (32-bit) arithmetic operations are supposed to take as its operands only the lowest 32 bits of the input registers.
However, in the division by zero code that requirement fails.
Observe that the switch statement only catches the case in which the input register **has all bits set to zero**. In reality, only the least significant 32 bits should be considered.
In the case any of the most significant 32 bits is set, the `switch` statement will follow the default path, and the division will be performed with the same behavior as an EVM division (except for sign extending) -- **that means …
> Use only the lowest 32 bit of input for 32 bit division operations

- rvgo/fast/state.go
The fast implementation calculates the state hash from the state witness in the StateWitness.StateHash function.
However, this function implements a length check that is insufficient. The expected length is known to be `362` but the implementation checks that the length is greater than `32 + 32 + 8 + 8 + 1 = 81`. We should check the state witness length is equal to the expected length.
> Fix state hash size check in fast implementation

- rvgo/fast/vm.go
- rvgo/slow/vm.go
- rvsol/src/RISCV.sol
- rvsol/test/RISCV.t.sol
As per specification: *"SLLIW, SRLIW, and SRAIW encodings with imm[5] != 0 are reserved"*.
However, implementations (sol/fast/slow) accept it.
This PR reverts the reserved SLLIW/SRLIW/SRAIW instructions with imm[5] != 0
> Revert reserved immediate word shifts with imm[5]!=0

- rvgo/slow/vm.go
The slow implementation loads the `_proof` length from calldata and checks that this length is a multiple of 60.
However, this check uses a logical AND which may lead to accepting invalid values that are not multiple of 60.
```solidity
if and(b32asBEWord(calldataload(shortToU64(uint16(stateContentOffset)+paddedStateSize))), shortToU256(60-1)) != (U256{}) {
```
Moreover, the check is insufficient. `_proof` is expected to be a multiple of `60 * 32`, however only the fact that it is a multiple of 60 is checked.
The logical AND check should be replaced with a modulo operation to ensure that it is a multiple of `32 * 60`.
> Use modulo instead of and operation to validate the proof size

- rvgo/fast/yul256.go
- rvgo/fast/yul64.go
Currently, a series of calculation functions on yul256.go - specifically add, div, sdiv, mod, smod, lt, gt, slt, sgt, eq, iszero, xor, sar are unused
However, these functions are meant to be used in the yul64.go, as slow and evm implementation has yul64 calculation functions inherited from the behavior from yul256 functions.
> Modify rvgo/fast/yul64.go implementation to use yul256 implementation like slow / evm

- rvgo/fast/vm.go
- rvgo/riscv/constants.go
- rvgo/slow/vm.go
- rvsol/src/RISCV.sol
- rvsol/test/RISCV.t.sol
In multiple opcodes handling, the behaviour of the virtual machine is unexpected when the instruction is not entirely recognized.
This type of unexpected behaviour is found in opcodes:
- 0x13, especially SR~ instructions
- 0x1B, especially SR~ instructions and when funct3 is not one of [0, 1, 5].
- 0x33, especially SR~ and ADD/SUB instructions
- 0x3B
- when funct7 == 1 and funct3 is not one of [0, 4, 5, 6, 7]
- when funct7 != 1 and instruction is SR~, ADDW/SUBW or not recognized.
This PR adds revert behavior to such unrecognized instruction encoding in rvgoand rvsol implementation.
> Revert instructions where encoding is unrecognized

- rvgo/slow/vm.go
- rvgo/test/evm_test.go
- rvgo/test/vm_test.go
Add tests to validate the VM proof sizes are correct which are added in https://github.com/ethereum-optimism/asterisc/pull/101 and https://github.com/ethereum-optimism/asterisc/pull/99
This test checks to see if the vm reverts when the proof size is not a multiple of 60*32.
> Add tests for checking vm proof sizes is multiple of 60*32

- README.md
- mise.toml
Before moving on to the migration Github Actions to CircleCI, I added `mise` as a dependency manager. `mise` is being used in the [`optimism` monorepo](https://github.com/ethereum-optimism/optimism/blob/develop/mise.toml), [supersim](https://github.com/ethereum-optimism/supersim) and others and provides a great way of managing tooling required for development.
It is an add-on, it does not break or affect any existing development flows, just provides a convenient way of setting up your development environment (as well as the CI environment).
> chore: Use mise for dependency management [1/N]

- .circleci/config.yml
~~**This PR builds on top of #133 and can be reviewed once that one is merged**~~
Replaces the CI builder image (slow) with development environment setup using `mise`. Also includes a tiny cleanup of redundant parameters of CircleCI workflows.
> chore: Use mise to setup CircleCI environment [2/N]

- .circleci/config.yml
Installing `go` modules is a common operation that can be isolated into its own command. This will simplify further migration to CircleCI as we keep porting new jobs over from Github Actions.
> chore: Add reusable install-go-modules job to CircleCI pipeline [3/N]

- .circleci/config.yml
- `go-mod-download-monorepo` job was, despite its name, lining `optimism` monorepo so it was dropped
- `go-mod-download-asterisc` job was just downloading the `go` modules so it was dropped
**Tests**
**Additional context**
**Metadata**
> chore: Clean up pipeline sequence [4/N]

- .circleci/config.yml
> chore: Migrate rvgo-tests workflow to CircleCI [5/N]

- .circleci/config.yml
> chore: Migrate rvsol-tests workflow to CircleCI [6/N]

- .circleci/config.yml
The E2E job sequence is the one that takes the longest and some of the jobs were not being executed on the large runners.
> chore: Increase resources for E2E tests CircleCI workflow [7/N]

- .circleci/config.yml
> chore: Migrate rvsol-lint workflow to CircleCI [8/N]

- .circleci/config.yml
> chore: Migrate rvgo-lint workflow to CircleCI [9/N]

- .circleci/config.yml
- mise.toml
> chore: Migrate rvgo-abigen workflow to CircleCI [10/N]

- .circleci/config.yml
> chore: Migrate op-program-test workflow to CircleCI [11/N]

- .circleci/config.yml
> chore: Migrate check-optimism-version-match workflow to CircleCI [12/N]
